/*
 * Copyright (c) 2022 Google Inc
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_RESET_CH32_RESET_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_RESET_CH32_RESET_H_

#define CH32_RCC_REG_BASE           0x40021000U

#define CH32_RCC_APB2RST_OFFSET     0x0CU
#define CH32_RCC_APB1RST_OFFSET     0x10U
#define CH32_RCC_AHBRST_OFFSET      0x28U

/**
 * Pack RCC register offset and bit in one 32-bit value.
 *
 * 5 LSBs are used to keep bit number in 32-bit RCC register.
 * Next 12 bits are used to keep RCC register offset.
 * Remaining bits are unused.
 *
 * @param bus CH32 bus name (expands to CH32_RCC{bus}_OFFSET)
 * @param bit Reset bit
 */
#define CH32_RESET_CONFIG(reg, bit) \
	(((CH32_RCC_ ## reg ## _OFFSET) << 6U) | (bit))


/**
 * @name Clock enable/disable definitions for peripherals
 * @{
 */

/* APB2 peripherals */
#define CH32_RESET_AFIO       CH32_RESET_CONFIG(APB2RST, 0U)
#define CH32_RESET_GPIOA      CH32_RESET_CONFIG(APB2RST, 2U)
#define CH32_RESET_GPIOB      CH32_RESET_CONFIG(APB2RST, 3U)
#define CH32_RESET_GPIOC      CH32_RESET_CONFIG(APB2RST, 4U)
#define CH32_RESET_GPIOD      CH32_RESET_CONFIG(APB2RST, 5U)
#define CH32_RESET_GPIOE      CH32_RESET_CONFIG(APB2RST, 6U)
#define CH32_RESET_ADC0       CH32_RESET_CONFIG(APB2RST, 9U)
#define CH32_RESET_ADC1       CH32_RESET_CONFIG(APB2RST, 10U)
#define CH32_RESET_TIMER0     CH32_RESET_CONFIG(APB2RST, 11U)
#define CH32_RESET_SPI0       CH32_RESET_CONFIG(APB2RST, 12U)
#define CH32_RESET_TIMER7     CH32_RESET_CONFIG(APB2RST, 13U)
#define CH32_RESET_USART0     CH32_RESET_CONFIG(APB2RST, 14U)

/* APB1 peripherals */
#define CH32_RESET_TIMER1     CH32_RESET_CONFIG(APB1RST, 0U)
#define CH32_RESET_TIMER2     CH32_RESET_CONFIG(APB1RST, 1U)
#define CH32_RESET_TIMER3     CH32_RESET_CONFIG(APB1RST, 2U)
#define CH32_RESET_TIMER4     CH32_RESET_CONFIG(APB1RST, 3U)
#define CH32_RESET_TIMER5     CH32_RESET_CONFIG(APB1RST, 4U)
#define CH32_RESET_TIMER6     CH32_RESET_CONFIG(APB1RST, 5U)
#define CH32_RESET_WWDGT      CH32_RESET_CONFIG(APB1RST, 11U)
#define CH32_RESET_SPI1       CH32_RESET_CONFIG(APB1RST, 14U)
#define CH32_RESET_SPI2       CH32_RESET_CONFIG(APB1RST, 15U)
#define CH32_RESET_USART1     CH32_RESET_CONFIG(APB1RST, 17U)
#define CH32_RESET_USART2     CH32_RESET_CONFIG(APB1RST, 18U)
#define CH32_RESET_UART3      CH32_RESET_CONFIG(APB1RST, 19U)
#define CH32_RESET_UART4      CH32_RESET_CONFIG(APB1RST, 20U)
#define CH32_RESET_I2C0       CH32_RESET_CONFIG(APB1RST, 21U)
#define CH32_RESET_I2C1       CH32_RESET_CONFIG(APB1RST, 22U)
#define CH32_RESET_CAN0       CH32_RESET_CONFIG(APB1RST, 25U)
#define CH32_RESET_CAN1       CH32_RESET_CONFIG(APB1RST, 26U)
#define CH32_RESET_BKPI       CH32_RESET_CONFIG(APB1RST, 27U)
#define CH32_RESET_PMU        CH32_RESET_CONFIG(APB1RST, 28U)
#define CH32_RESET_DAC        CH32_RESET_CONFIG(APB1RST, 29U)

/* AHB peripherals */
#define CH32_RESET_USBFS      CH32_RESET_CONFIG(AHBRST, 12U)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_RESET_CH32_RESET_H_ */
