/*
 * Copyright (c)
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_CH32_CLOCKS_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_CH32_CLOCKS_H_

/**
 * @name Register offsets
 * @{
 */
#define CH32_RCC_BASE               0x40021000U
#define CH32_RCC_AHBEN_OFFSET       0x14U
#define CH32_RCC_APB2EN_OFFSET      0x18U
#define CH32_RCC_APB1EN_OFFSET      0x1CU

#define CH32_PERIPH_BUS_MIN         CH32_RCC_BASE
#define CH32_PERIPH_BUS_MAX         (CH32_RCC_BASE + CH32_RCC_APB1EN_OFFSET)
/**
 * Encode RCC register offset and configuration bit.
 *
 * - 0..5: bit number
 * - 6..14: offset
 * - 15: reserved
 *
 * @param reg RCC register name (expands to CH32_{reg}_OFFSET)
 * @param bit Configuration bit
 */
#define CH32_CLOCK_CONFIG(reg, bit) \
	(((CH32_RCC_ ## reg ## _OFFSET) << 6U) | (bit))

/**
 * @name Clock enable/disable definitions for peripherals
 * @{
 */
/* AHB peripherals */
#define CH32_CLOCK_DMA1         CH32_CLOCK_CONFIG(AHBEN, 0U)
#define CH32_CLOCK_DMA2         CH32_CLOCK_CONFIG(AHBEN, 1U)
#define CH32_CLOCK_SRAM         CH32_CLOCK_CONFIG(AHBEN, 2U)
#define CH32_CLOCK_CRC          CH32_CLOCK_CONFIG(AHBEN, 6U)
#define CH32_CLOCK_FSMC         CH32_CLOCK_CONFIG(AHBEN, 8U)
#define CH32_CLOCK_RNG          CH32_CLOCK_CONFIG(AHBEN, 9U)
#define CH32_CLOCK_SDIO         CH32_CLOCK_CONFIG(AHBEN, 10U)
#define CH32_CLOCK_USBHS        CH32_CLOCK_CONFIG(AHBEN, 11U)
#define CH32_CLOCK_USBFS        CH32_CLOCK_CONFIG(AHBEN, 12U)
#define CH32_CLOCK_DVP          CH32_CLOCK_CONFIG(AHBEN, 13U)
#define CH32_CLOCK_ETHMAC       CH32_CLOCK_CONFIG(AHBEN, 14U)
#define CH32_CLOCK_ETHMACTX     CH32_CLOCK_CONFIG(AHBEN, 15U)
#define CH32_CLOCK_ETHMACRX     CH32_CLOCK_CONFIG(AHBEN, 16U)
#define CH32_CLOCK_BLES         CH32_CLOCK_CONFIG(AHBEN, 17U)

/* APB1 peripherals */
#define CH32_CLOCK_TIM2         CH32_CLOCK_CONFIG(APB1EN, 0U)
#define CH32_CLOCK_TIM3         CH32_CLOCK_CONFIG(APB1EN, 1U)
#define CH32_CLOCK_TIM4         CH32_CLOCK_CONFIG(APB1EN, 2U)
#define CH32_CLOCK_TIM5         CH32_CLOCK_CONFIG(APB1EN, 3U)
#define CH32_CLOCK_TIM6         CH32_CLOCK_CONFIG(APB1EN, 4U)
#define CH32_CLOCK_TIM7         CH32_CLOCK_CONFIG(APB1EN, 5U)
#define CH32_CLOCK_USART6       CH32_CLOCK_CONFIG(APB1EN, 6U)
#define CH32_CLOCK_USART7       CH32_CLOCK_CONFIG(APB1EN, 7U)
#define CH32_CLOCK_USART8       CH32_CLOCK_CONFIG(APB1EN, 8U)
#define CH32_CLOCK_WWDG         CH32_CLOCK_CONFIG(APB1EN, 11U)
#define CH32_CLOCK_SPI2         CH32_CLOCK_CONFIG(APB1EN, 14U)
#define CH32_CLOCK_SPI3         CH32_CLOCK_CONFIG(APB1EN, 15U)
#define CH32_CLOCK_USART2       CH32_CLOCK_CONFIG(APB1EN, 17U)
#define CH32_CLOCK_USART3       CH32_CLOCK_CONFIG(APB1EN, 18U)
#define CH32_CLOCK_USART4       CH32_CLOCK_CONFIG(APB1EN, 19U)
#define CH32_CLOCK_USART5       CH32_CLOCK_CONFIG(APB1EN, 20U)
#define CH32_CLOCK_I2C1         CH32_CLOCK_CONFIG(APB1EN, 21U)
#define CH32_CLOCK_I2C2         CH32_CLOCK_CONFIG(APB1EN, 22U)
#define CH32_CLOCK_USBD         CH32_CLOCK_CONFIG(APB1EN, 23U)
#define CH32_CLOCK_CAN1         CH32_CLOCK_CONFIG(APB1EN, 25U)
#define CH32_CLOCK_CAN2         CH32_CLOCK_CONFIG(APB1EN, 26U)
#define CH32_CLOCK_BKP          CH32_CLOCK_CONFIG(APB1EN, 27U)
#define CH32_CLOCK_PWR          CH32_CLOCK_CONFIG(APB1EN, 28U)
#define CH32_CLOCK_DAC          CH32_CLOCK_CONFIG(APB1EN, 29U)


/* APB2 peripherals */
#define CH32_CLOCK_AFIO         CH32_CLOCK_CONFIG(APB2EN, 0U)
#define CH32_CLOCK_GPIOA        CH32_CLOCK_CONFIG(APB2EN, 2U)
#define CH32_CLOCK_GPIOB        CH32_CLOCK_CONFIG(APB2EN, 3U)
#define CH32_CLOCK_GPIOC        CH32_CLOCK_CONFIG(APB2EN, 4U)
#define CH32_CLOCK_GPIOD        CH32_CLOCK_CONFIG(APB2EN, 5U)
#define CH32_CLOCK_GPIOE        CH32_CLOCK_CONFIG(APB2EN, 6U)
#define CH32_CLOCK_ADC1         CH32_CLOCK_CONFIG(APB2EN, 9U)
#define CH32_CLOCK_ADC2         CH32_CLOCK_CONFIG(APB2EN, 10U)
#define CH32_CLOCK_TIM1         CH32_CLOCK_CONFIG(APB2EN, 11U)
#define CH32_CLOCK_SPI1         CH32_CLOCK_CONFIG(APB2EN, 12U)
#define CH32_CLOCK_TIM8         CH32_CLOCK_CONFIG(APB2EN, 13U)
#define CH32_CLOCK_USART1       CH32_CLOCK_CONFIG(APB2EN, 14U)
#define CH32_CLOCK_TIM9         CH32_CLOCK_CONFIG(APB2EN, 19U)
#define CH32_CLOCK_TIM10        CH32_CLOCK_CONFIG(APB2EN, 20U)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_CH32_CLOCKS_H_ */
